/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ART_LOLL (https://sketchfab.com/evgenytvidov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nemo-cyborg-has-a-skeleton-blender-a55d5eb3c9d94840a14c53d9c85b95a2
Title: Nemo - cyborg has a skeleton Blender.
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';

export default function NemoCyborg(props) {
  const { nodes, materials } = useGLTF('/models/nemo-scene-transformed.glb');

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    modelRef.current.rotation.y += 0.005;
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0, -1.5, 1]}
    scale={[1.5, 1.5, 1.5,]}
    rotation={[0, 0.30, 0]}
    >
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.Head}
        skeleton={nodes.Object_7.skeleton}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_8.geometry}
        material={materials.Body}
        skeleton={nodes.Object_8.skeleton}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/nemo-scene-transformed.glb')
