/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BlackHawk0512 (https://sketchfab.com/BlackHawk0512)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ufo-flying-saucer-spaceship-ovni-094ce2baf6ee40aa8f083b7d0fcf0a9f
Title: UFO Flying Saucer Spaceship OVNI
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Ufo(props) {
  const { nodes, materials } = useGLTF('/models/ufo-scene-transformed.glb')

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    modelRef.current.rotation.y += 0.005;
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0, 0.5, 0.5]}
    scale={[0.4, 0.4, 0.4]}
    rotation={[0, 0.5, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UFO_Ventanilla_0.geometry}
        material={materials.Ventanilla}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UFO_UFO_Metal_0.geometry}
        material={materials.UFO_Metal}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UFO_UFO_BLACK_0.geometry}
        material={materials.UFO_BLACK}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/models/ufo-scene-transformed.glb');