/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Enalrem (https://sketchfab.com/enalrem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyborg-weapon-8bf111f38ff34ad38068739819fdaf0d
Title: Cyborg Weapon
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Weapon(props) {
  const { nodes, materials } = useGLTF('/models/weapon-scene-transformed.glb')
  return (
    <group {...props} dispose={null}
    scale={[10, 10, 10]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cyborg_Weapon_Cyborg_Weapon_mat_0.geometry}
        material={materials.Cyborg_Weapon_mat}
      />
    </group>
  )
}

useGLTF.preload('/models/weapon-scene-transformed.glb')