/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Enalrem (https://sketchfab.com/enalrem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyborg-weapon-8bf111f38ff34ad38068739819fdaf0d
Title: Cyborg Weapon
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Weapon(props) {
  const { nodes, materials } = useGLTF('/models/weapon-scene-transformed.glb');
  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.008;
  })
  return (
    <group {...props} dispose={null}
    scale={[2,2,2]}
    position={[0, 1, 0]}
    ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cyborg_Weapon_Cyborg_Weapon_mat_0.geometry}
        material={materials.Cyborg_Weapon_mat}
      />
    </group>
  )
}

useGLTF.preload('/models/weapon-scene-transformed.glb')